export interface WizardPalette {
  [key: string]: string
}

export interface WizardType {
  id: string
  name: string
  description: string
  minLevel: number
  palette: WizardPalette
  pixels: string[]
}

const NOVICE_PALETTE: WizardPalette = {
  '.': 'transparent',
  g: '#6B7280', G: '#4B5563', h: '#9CA3AF',
  s: '#F5D6C6', S: '#E8B88A', e: '#1A1A1A',
  m: '#4A4036', n: '#6B5B45',
  a: '#8B7355', A: '#7A6345', c: '#5A4325',
  b: '#8B6F47', B: '#A88B5F',
  f: '#6B4226', F: '#5A3216',
}

const NOVICE_PIXELS = [
  '............................',
  '............................',
  '..........GGGGG.............',
  '.........GGGGGGG............',
  '........GGGGGGGGG...........',
  '........GGGGGGGGG...........',
  '.......GGGGGGGGGGG..........',
  '.......GGGGGGGGGGG..........',
  '......GGGGGGGGGGGGG.........',
  '......GGGGGGGGGGGGG.........',
  '......GGGGGGGGGGGGG.........',
  '.......GGGgGGGgGGG..........',
  '.......gGGGGGGGGGg..........',
  '........ggggggggg...........',
  '.........sssssss............',
  '........sSesSesS............',
  '........ssssssss............',
  '.......sSssssssSs...........',
  '........ssssssss............',
  '.........mnmnm..............',
  '........nnnnnnn.............',
  '.......anaaaaana............',
  '.......naaaaaaan............',
  '......anaaaaaaaana..........',
  '......naaaaaaaaan...........',
  '.....anaaaaaaaaaana.........',
  '.....naaacccaaaan...........',
  '....anaaaaaaaaaaaana........',
  '.....naaaaaaaaanaan.........',
  '......aaaaacccaaaa..........',
  '......ffccffccff............',
  '......ffccffccff............',
  '............................',
  '............................',
]

const WIZARD_PALETTE: WizardPalette = {
  '.': 'transparent',
  t: '#3D6F99', T: '#4A7DB4', h: '#6A9DD4', H: '#7DB0D6',
  g: '#C8A84E', G: '#E8C86E', Y: '#FFE880',
  s: '#F5D6C6', S: '#E8B88A', e: '#1A1A1A',
  r: '#3D6F99', R: '#5B8DB8', L: '#7DB0D6', d: '#2D5A8A',
  b: '#8B6F47', B: '#A88B5F', D: '#6B4F27',
  f: '#6B4226', F: '#5A3216',
  y: '#F0D060', w: '#B8D8F0',
  '*': '#FFFFFF',
}

const WIZARD_PIXELS = [
  '............................',
  '..........TTTTT.............',
  '.........ThhhhT.............',
  '........ThhhhhhT............',
  '.......ThhhhhhhhT...........',
  '.......ThhhhhhhhT...........',
  '......ThhhhhhhhhhT..........',
  '......ThhhhhhhhhhT..........',
  '......ThhhhhhhhhhT..........',
  '......TThhhhhhhhTT..........',
  '.......tTThhhhTTt...........',
  '........gggggggg............',
  '.......gGGGGGGGGg...........',
  '......gGGGGGGGGGGg..........',
  '.......ssssssssss...........',
  '......sSe..e..eSs...........',
  '......sssssssssss...........',
  '......sSsssssssSs...........',
  '.......sssssssss............',
  '........rrdrr...............',
  '.......rrrrrrr..............',
  '......rRrrrrrRr.............',
  '......rLLLLLLLr.....bB......',
  '.....rrrrrrrrrrr...bBBb.....',
  '....rRrRrRrRrRrR...bBCb.....',
  '....rLLLLLLLLLLLr...bBb.....',
  '.....rrrrrrrrrrr.....b......',
  '......rRRRRRRRRr............',
  '.......rrrrrrrrr............',
  '........rrddrrd.............',
  '........ff..ff..............',
  '........ff..ff..............',
  '............................',
  '............................',
]

const ARCHMAGE_PALETTE: WizardPalette = {
  '.': 'transparent',
  p: '#7B4F9E', P: '#9B6FBE', u: '#5B2F7E', U: '#BB8FDE',
  g: '#C8A84E', G: '#E8C86E', Y: '#FFE880',
  s: '#F5D6C6', S: '#E8B88A', e: '#1A1A1A',
  r: '#6B3F8E', R: '#8B5FAE', L: '#AB7FCE', d: '#4B2F6E',
  b: '#8B6F47', B: '#A88B5F', D: '#6B4F27',
  f: '#6B4226', F: '#5A3216',
  c: '#FF69B4', C: '#FF8EC4',
  y: '#F0D060', w: '#D8B8F0',
  '*': '#FFFFFF',
}

const ARCHMAGE_PIXELS = [
  '............................',
  '...........uuu..............',
  '..........upppp.............',
  '.........upppppp............',
  '........upppppppp...........',
  '.......upppppppppp..........',
  '.......upppppppppp..........',
  '......upppppppppppp.........',
  '......upppppppppppp.........',
  '......upppppppppppp.........',
  '......upppppppppppp.........',
  '.......uuppppppuu...........',
  '........gGGGGGGg............',
  '.......gGGGGGGGGg...........',
  '........ssssssss............',
  '.......sSe..e..es...........',
  '.......ssssssssss...........',
  '.......sSssssssSs...........',
  '........ssssssss............',
  '.......r.rrrr.r.............',
  '......rrr.rrrrrr............',
  '.....rRrrrrrrrRr............',
  '.....rLLLLLLLr...cBCb.......',
  '....rrrrrrrrrrrr.bCccCb.....',
  '...rRrRrRrRrRrR..bCccCb.....',
  '...rLLLLLLLLLLLr..bBCb......',
  '....rrrrrrrrrrr....bBb......',
  '.....rRRRRRRRRr.............',
  '......rrrrrrrrr.............',
  '.......rrddrr...............',
  '.......ff..ff...............',
  '.......ff..ff...............',
  '............................',
  '............................',
]

const GRANDMASTER_PALETTE: WizardPalette = {
  '.': 'transparent',
  i: '#B22222', I: '#DC143C', o: '#8B0000', O: '#FF4444',
  g: '#C8A84E', G: '#E8C86E', Y: '#FFE880',
  s: '#F5D6C6', S: '#E8B88A', e: '#1A1A1A',
  r: '#A02020', R: '#C04040', L: '#E06060', d: '#801010',
  b: '#8B6F47', B: '#A88B5F', D: '#6B4F27',
  f: '#6B4226', F: '#5A3216',
  c: '#FFD700', C: '#FFA500', w: '#FF6666',
  x: '#FF4400', X: '#FF6600',
  y: '#F0D060', z: '#FF8844',
  '*': '#FFFFFF',
}

const GRANDMASTER_PIXELS = [
  '........oOOO................',
  '.......oiiiiO...............',
  '......oiiiiiiiO.............',
  '.....oiiiiiiiiiO............',
  '.....oiiiiiiiiiO............',
  '....oiiiiiiiiiiiO...........',
  '....oiiiiiiiiiiiO...........',
  '....oIIIIIIIIIIIO...........',
  '....oiiGGGGGGiiO............',
  '.....oOGGGGGGOo.............',
  '.......ccccc................',
  '......ccccccccc.............',
  '.....c.cccccccc.c...........',
  '......sssssssss.............',
  '.....sSe..e..esS............',
  '.....sssssssssss............',
  '.....sSsssssssSs............',
  '......sssssssss.............',
  '.....rrr.rrrrr..............',
  '....rrrrrrrrrrrr............',
  '...rRrrrrrrrrrRr............',
  '...rLLLLLLLr..cBc...........',
  '..rrrrrrrrrrrr.bCcb.........',
  '..rRrRrRrRrRrR.bCccb........',
  '..rLLLLLLLLLLLr.bCcb........',
  '...rrrrrrrrrrr..cBc.........',
  '....rRRRRRRRRr..............',
  '.....rrrrrrrrr..............',
  '......rrddrr................',
  '......ff..ff................',
  '......ff..ff................',
  '............................',
  '............................',
  '............................',
]

const OVERLORD_PALETTE: WizardPalette = {
  '.': 'transparent',
  n: '#2D1B4E', N: '#4A2D6E', m: '#1A0A2E', M: '#6B4D8E',
  g: '#C8A84E', G: '#E8C86E',
  s: '#E8B88A', S: '#D4A578', e: '#00FF88', E: '#00CC66',
  r: '#3D1B5E', R: '#5D3B7E', L: '#7D5B9E', d: '#1D0B3E',
  b: '#4A3A2A', B: '#6A5A4A', D: '#2A1A0A',
  f: '#3A2216', F: '#2A1206',
  c: '#00FF88', C: '#00CC66',
  y: '#F0D060', Y: '#FFE880',
  '*': '#00FFAA',
}

const OVERLORD_PIXELS = [
  '............................',
  '........nnmmnmnn............',
  '.......mnnnnnnnnm...........',
  '......mnnnnnnnnnnm..........',
  '......mnnnnnnnnnnm..........',
  '.....mnnnnnnnnnnnnm.........',
  '....mnnnnnnnnnnnnnnm........',
  '....mNnnnnnnnnnnnNm.........',
  '....mNnnnnnnnnnnnNm.........',
  '....mnnnnGGGGGnnnm..........',
  '.....mmmnnnnnnmmm...........',
  '.......mmmmmmmmm............',
  '........sssssss.............',
  '.......sSe*e*esS............',
  '.......sssssssss............',
  '.......sSsssssSs............',
  '........sssssss.............',
  '.......rrrrrrrr.............',
  '......rrrrrrrrrrr...........',
  '.....rRrrrrrrrrRr...........',
  '....rRrrrrrrrrrrRr..........',
  '....rLLLLLLLr...cCc.........',
  '...rrrrrrrrrrr..cCccC.......',
  '...rRrRrRrRrRr..cCccC.......',
  '...rLLLLLLLLLLLr..cCc.......',
  '....rrrrrrrrrrr..cCcc.......',
  '.....rRRRRRRRRr..cCc........',
  '......rrrrrrrrr.............',
  '.......rrrddrr..............',
  '.......ff..ff...............',
  '.......ff..ff...............',
  '............................',
  '............................',
  '............................',
]

const DEITY_PALETTE: WizardPalette = {
  '.': 'transparent',
  z: '#FFD700', Z: '#FFA500', x: '#FFFFFF', X: '#FFF8DC',
  h: '#FFFACD', H: '#FFFFF0',
  s: '#F5D6C6', S: '#E8B88A', e: '#1A1A1A',
  r: '#FFF8DC', R: '#FFFACD', L: '#FFFFF0', d: '#F5DEB3',
  g: '#FFD700', G: '#FFEE88',
  b: '#DAA520', B: '#FFD700', D: '#B8860B',
  f: '#DAA520', F: '#B8860B',
  y: '#FFEE88', Y: '#FFFFAA',
  w: '#FFFFFF', v: '#FFFACD',
  '*': '#FFFFFF',
  '@': '#E0F0FF',
}

const DEITY_PIXELS = [
  '............@@@..............',
  '..........@@@@@@@............',
  '.........@@.....@@...........',
  '........@@.......@@..........',
  '.............zzz.............',
  '............zzzzz............',
  '...........zxxxz.............',
  '..........zxxxxxz............',
  '.........zxxxxxxz............',
  '.........zzzzzzzz............',
  '..........gGGGGg.............',
  '.........gGGGGGGg............',
  '.......gGGGGGGGGGg...........',
  '........sssssssss............',
  '.......sSe..e..esS...........',
  '.......sssssssssss...........',
  '.......sSsssssssSs...........',
  '........sssssssss............',
  '.......rrrrrrrrr.............',
  '......rrrrrrrrrrr............',
  '.....rRrrrrrrrrRr............',
  '....rRrRrRrRrRrRr............',
  '....rLLLLLLLLLLLr..bBb.......',
  '...rrrrrrrrrrrrrr..bBb.......',
  '...rRrRrRrRrRrRr..bBb........',
  '...rLLLLLLLLLLLLLr.bBb.......',
  '....rrrrrrrrrrrrr..bBb.......',
  '.....rRRRRRRRRRr.............',
  '......rrrrrrrrrr.............',
  '.......rrddrrr...............',
  '........ff..ff...............',
  '........ff..ff...............',
  '.............................',
  '.............................',
]

export const WIZARD_TYPES: WizardType[] = [
  {
    id: 'novice',
    name: 'Novice',
    description: 'Data Novice',
    minLevel: 1,
    palette: NOVICE_PALETTE,
    pixels: NOVICE_PIXELS,
  },
  {
    id: 'wizard',
    name: 'Wizard',
    description: 'Data Wizard',
    minLevel: 5,
    palette: WIZARD_PALETTE,
    pixels: WIZARD_PIXELS,
  },
  {
    id: 'archmage',
    name: 'Archmage',
    description: 'Query Architect',
    minLevel: 15,
    palette: ARCHMAGE_PALETTE,
    pixels: ARCHMAGE_PIXELS,
  },
  {
    id: 'grandmaster',
    name: 'Grandmaster',
    description: 'Grandmaster of Data',
    minLevel: 30,
    palette: GRANDMASTER_PALETTE,
    pixels: GRANDMASTER_PIXELS,
  },
  {
    id: 'overlord',
    name: 'Overlord',
    description: 'DBA Overlord',
    minLevel: 50,
    palette: OVERLORD_PALETTE,
    pixels: OVERLORD_PIXELS,
  },
  {
    id: 'deity',
    name: 'Deity',
    description: 'God of Data',
    minLevel: 75,
    palette: DEITY_PALETTE,
    pixels: DEITY_PIXELS,
  },
]

export const getWizardType = (level: number): WizardType => {
  const wizard = [...WIZARD_TYPES]
    .reverse()
    .find(w => level >= w.minLevel)
  return wizard ?? WIZARD_TYPES[0]
}
