export const MONGODB_TYPES = [
  'String',
  'Int32',
  'Int64',
  'Double',
  'Decimal128',
  'Boolean',
  'ObjectId',
  'DateTime',
  'Timestamp',
  'Array',
  'Object',
  'Null',
  'Binary',
  'RegularExpression',
  'JavaScript',
  'Symbol',
  'MinKey',
  'MaxKey',
  'Undefined',
]

export const MONGO_TYPE_VALUES: Record<string, unknown> = {
  String: '',
  Int32: 0,
  Int64: 0,
  Double: 0.5,
  Decimal128: 0.5,
  Boolean: false,
  Null: null,
  Array: [],
  Object: {},
  ObjectId: { $oid: '000000000000000000000000' },
  DateTime: { $date: '1970-01-01T00:00:00.000Z' },
  Timestamp: { $timestamp: { t: 0, i: 0 } },
  Binary: { $binary: { base64: '', subType: '00' } },
  RegularExpression: { $regularExpression: { pattern: '', options: '' } },
  JavaScript: { $code: '' },
  Symbol: { $symbol: '' },
  MinKey: { $minKey: 1 },
  MaxKey: { $maxKey: 1 },
  Undefined: { $undefined: true },
}
